# Generated by Django 4.2.2 on 2023-06-11 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0004_alter_resell_book_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resell_book',
            name='user',
        ),
    ]
