# Generated by Django 4.2.2 on 2023-06-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookForSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='book_images')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('offer', models.BooleanField(default=False)),
                ('used', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(default='No description provided')),
                ('preview_1', models.ImageField(blank=True, null=True, upload_to='book_images')),
                ('preview_2', models.ImageField(blank=True, null=True, upload_to='book_images')),
            ],
        ),
    ]
