# Generated by Django 4.2.2 on 2023-06-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsale',
            name='offer',
            field=models.BooleanField(default=False),
        ),
    ]
