# Generated by Django 4.2.2 on 2023-06-20 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0002_bookforsale_preview_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsale',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
