# Generated by Django 4.2.2 on 2023-06-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0002_bookforsale_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsale',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
