# Generated by Django 4.2.2 on 2023-06-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0003_bookforsale_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsale',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
