# Generated by Django 4.2.2 on 2023-07-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shop', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookforsale',
            name='author',
            field=models.CharField(default='No author provided', max_length=100),
        ),
    ]
